// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileUpload.proto

package com.senthuran.GRPCFileUpload;

public interface FileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:File)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes content = 1;</code>
   */
  com.google.protobuf.ByteString getContent();
}
