// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileUpload.proto

package com.senthuran.GRPCFileUpload;

public interface FileUploadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FileUploadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.Status status = 2;</code>
   */
  int getStatusValue();
  /**
   * <code>.Status status = 2;</code>
   */
  com.senthuran.GRPCFileUpload.Status getStatus();
}
