// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileUpload.proto

package com.senthuran.GRPCFileUpload;

/**
 * Protobuf type {@code FileUploadRequest}
 */
public  final class FileUploadRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FileUploadRequest)
    FileUploadRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FileUploadRequest.newBuilder() to construct.
  private FileUploadRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FileUploadRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FileUploadRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.senthuran.GRPCFileUpload.MetaData.Builder subBuilder = null;
            if (requestCase_ == 1) {
              subBuilder = ((com.senthuran.GRPCFileUpload.MetaData) request_).toBuilder();
            }
            request_ =
                input.readMessage(com.senthuran.GRPCFileUpload.MetaData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.senthuran.GRPCFileUpload.MetaData) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 1;
            break;
          }
          case 18: {
            com.senthuran.GRPCFileUpload.File.Builder subBuilder = null;
            if (requestCase_ == 2) {
              subBuilder = ((com.senthuran.GRPCFileUpload.File) request_).toBuilder();
            }
            request_ =
                input.readMessage(com.senthuran.GRPCFileUpload.File.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.senthuran.GRPCFileUpload.File) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 2;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.senthuran.GRPCFileUpload.FileUpload.internal_static_FileUploadRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.senthuran.GRPCFileUpload.FileUpload.internal_static_FileUploadRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.senthuran.GRPCFileUpload.FileUploadRequest.class, com.senthuran.GRPCFileUpload.FileUploadRequest.Builder.class);
  }

  private int requestCase_ = 0;
  private java.lang.Object request_;
  public enum RequestCase
      implements com.google.protobuf.Internal.EnumLite {
    METADATA(1),
    FILE(2),
    REQUEST_NOT_SET(0);
    private final int value;
    private RequestCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static RequestCase forNumber(int value) {
      switch (value) {
        case 1: return METADATA;
        case 2: return FILE;
        case 0: return REQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public RequestCase
  getRequestCase() {
    return RequestCase.forNumber(
        requestCase_);
  }

  public static final int METADATA_FIELD_NUMBER = 1;
  /**
   * <code>.MetaData metadata = 1;</code>
   */
  public boolean hasMetadata() {
    return requestCase_ == 1;
  }
  /**
   * <code>.MetaData metadata = 1;</code>
   */
  public com.senthuran.GRPCFileUpload.MetaData getMetadata() {
    if (requestCase_ == 1) {
       return (com.senthuran.GRPCFileUpload.MetaData) request_;
    }
    return com.senthuran.GRPCFileUpload.MetaData.getDefaultInstance();
  }
  /**
   * <code>.MetaData metadata = 1;</code>
   */
  public com.senthuran.GRPCFileUpload.MetaDataOrBuilder getMetadataOrBuilder() {
    if (requestCase_ == 1) {
       return (com.senthuran.GRPCFileUpload.MetaData) request_;
    }
    return com.senthuran.GRPCFileUpload.MetaData.getDefaultInstance();
  }

  public static final int FILE_FIELD_NUMBER = 2;
  /**
   * <code>.File file = 2;</code>
   */
  public boolean hasFile() {
    return requestCase_ == 2;
  }
  /**
   * <code>.File file = 2;</code>
   */
  public com.senthuran.GRPCFileUpload.File getFile() {
    if (requestCase_ == 2) {
       return (com.senthuran.GRPCFileUpload.File) request_;
    }
    return com.senthuran.GRPCFileUpload.File.getDefaultInstance();
  }
  /**
   * <code>.File file = 2;</code>
   */
  public com.senthuran.GRPCFileUpload.FileOrBuilder getFileOrBuilder() {
    if (requestCase_ == 2) {
       return (com.senthuran.GRPCFileUpload.File) request_;
    }
    return com.senthuran.GRPCFileUpload.File.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestCase_ == 1) {
      output.writeMessage(1, (com.senthuran.GRPCFileUpload.MetaData) request_);
    }
    if (requestCase_ == 2) {
      output.writeMessage(2, (com.senthuran.GRPCFileUpload.File) request_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.senthuran.GRPCFileUpload.MetaData) request_);
    }
    if (requestCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.senthuran.GRPCFileUpload.File) request_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.senthuran.GRPCFileUpload.FileUploadRequest)) {
      return super.equals(obj);
    }
    com.senthuran.GRPCFileUpload.FileUploadRequest other = (com.senthuran.GRPCFileUpload.FileUploadRequest) obj;

    if (!getRequestCase().equals(other.getRequestCase())) return false;
    switch (requestCase_) {
      case 1:
        if (!getMetadata()
            .equals(other.getMetadata())) return false;
        break;
      case 2:
        if (!getFile()
            .equals(other.getFile())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (requestCase_) {
      case 1:
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + getMetadata().hashCode();
        break;
      case 2:
        hash = (37 * hash) + FILE_FIELD_NUMBER;
        hash = (53 * hash) + getFile().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.senthuran.GRPCFileUpload.FileUploadRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senthuran.GRPCFileUpload.FileUploadRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senthuran.GRPCFileUpload.FileUploadRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senthuran.GRPCFileUpload.FileUploadRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senthuran.GRPCFileUpload.FileUploadRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senthuran.GRPCFileUpload.FileUploadRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senthuran.GRPCFileUpload.FileUploadRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.senthuran.GRPCFileUpload.FileUploadRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.senthuran.GRPCFileUpload.FileUploadRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.senthuran.GRPCFileUpload.FileUploadRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.senthuran.GRPCFileUpload.FileUploadRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.senthuran.GRPCFileUpload.FileUploadRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.senthuran.GRPCFileUpload.FileUploadRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FileUploadRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FileUploadRequest)
      com.senthuran.GRPCFileUpload.FileUploadRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.senthuran.GRPCFileUpload.FileUpload.internal_static_FileUploadRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.senthuran.GRPCFileUpload.FileUpload.internal_static_FileUploadRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.senthuran.GRPCFileUpload.FileUploadRequest.class, com.senthuran.GRPCFileUpload.FileUploadRequest.Builder.class);
    }

    // Construct using com.senthuran.GRPCFileUpload.FileUploadRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestCase_ = 0;
      request_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.senthuran.GRPCFileUpload.FileUpload.internal_static_FileUploadRequest_descriptor;
    }

    @java.lang.Override
    public com.senthuran.GRPCFileUpload.FileUploadRequest getDefaultInstanceForType() {
      return com.senthuran.GRPCFileUpload.FileUploadRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.senthuran.GRPCFileUpload.FileUploadRequest build() {
      com.senthuran.GRPCFileUpload.FileUploadRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.senthuran.GRPCFileUpload.FileUploadRequest buildPartial() {
      com.senthuran.GRPCFileUpload.FileUploadRequest result = new com.senthuran.GRPCFileUpload.FileUploadRequest(this);
      if (requestCase_ == 1) {
        if (metadataBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = metadataBuilder_.build();
        }
      }
      if (requestCase_ == 2) {
        if (fileBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = fileBuilder_.build();
        }
      }
      result.requestCase_ = requestCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.senthuran.GRPCFileUpload.FileUploadRequest) {
        return mergeFrom((com.senthuran.GRPCFileUpload.FileUploadRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.senthuran.GRPCFileUpload.FileUploadRequest other) {
      if (other == com.senthuran.GRPCFileUpload.FileUploadRequest.getDefaultInstance()) return this;
      switch (other.getRequestCase()) {
        case METADATA: {
          mergeMetadata(other.getMetadata());
          break;
        }
        case FILE: {
          mergeFile(other.getFile());
          break;
        }
        case REQUEST_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.senthuran.GRPCFileUpload.FileUploadRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.senthuran.GRPCFileUpload.FileUploadRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int requestCase_ = 0;
    private java.lang.Object request_;
    public RequestCase
        getRequestCase() {
      return RequestCase.forNumber(
          requestCase_);
    }

    public Builder clearRequest() {
      requestCase_ = 0;
      request_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        com.senthuran.GRPCFileUpload.MetaData, com.senthuran.GRPCFileUpload.MetaData.Builder, com.senthuran.GRPCFileUpload.MetaDataOrBuilder> metadataBuilder_;
    /**
     * <code>.MetaData metadata = 1;</code>
     */
    public boolean hasMetadata() {
      return requestCase_ == 1;
    }
    /**
     * <code>.MetaData metadata = 1;</code>
     */
    public com.senthuran.GRPCFileUpload.MetaData getMetadata() {
      if (metadataBuilder_ == null) {
        if (requestCase_ == 1) {
          return (com.senthuran.GRPCFileUpload.MetaData) request_;
        }
        return com.senthuran.GRPCFileUpload.MetaData.getDefaultInstance();
      } else {
        if (requestCase_ == 1) {
          return metadataBuilder_.getMessage();
        }
        return com.senthuran.GRPCFileUpload.MetaData.getDefaultInstance();
      }
    }
    /**
     * <code>.MetaData metadata = 1;</code>
     */
    public Builder setMetadata(com.senthuran.GRPCFileUpload.MetaData value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        metadataBuilder_.setMessage(value);
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.MetaData metadata = 1;</code>
     */
    public Builder setMetadata(
        com.senthuran.GRPCFileUpload.MetaData.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.MetaData metadata = 1;</code>
     */
    public Builder mergeMetadata(com.senthuran.GRPCFileUpload.MetaData value) {
      if (metadataBuilder_ == null) {
        if (requestCase_ == 1 &&
            request_ != com.senthuran.GRPCFileUpload.MetaData.getDefaultInstance()) {
          request_ = com.senthuran.GRPCFileUpload.MetaData.newBuilder((com.senthuran.GRPCFileUpload.MetaData) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 1) {
          metadataBuilder_.mergeFrom(value);
        }
        metadataBuilder_.setMessage(value);
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.MetaData metadata = 1;</code>
     */
    public Builder clearMetadata() {
      if (metadataBuilder_ == null) {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
        }
        metadataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.MetaData metadata = 1;</code>
     */
    public com.senthuran.GRPCFileUpload.MetaData.Builder getMetadataBuilder() {
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <code>.MetaData metadata = 1;</code>
     */
    public com.senthuran.GRPCFileUpload.MetaDataOrBuilder getMetadataOrBuilder() {
      if ((requestCase_ == 1) && (metadataBuilder_ != null)) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 1) {
          return (com.senthuran.GRPCFileUpload.MetaData) request_;
        }
        return com.senthuran.GRPCFileUpload.MetaData.getDefaultInstance();
      }
    }
    /**
     * <code>.MetaData metadata = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.senthuran.GRPCFileUpload.MetaData, com.senthuran.GRPCFileUpload.MetaData.Builder, com.senthuran.GRPCFileUpload.MetaDataOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        if (!(requestCase_ == 1)) {
          request_ = com.senthuran.GRPCFileUpload.MetaData.getDefaultInstance();
        }
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.senthuran.GRPCFileUpload.MetaData, com.senthuran.GRPCFileUpload.MetaData.Builder, com.senthuran.GRPCFileUpload.MetaDataOrBuilder>(
                (com.senthuran.GRPCFileUpload.MetaData) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 1;
      onChanged();;
      return metadataBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.senthuran.GRPCFileUpload.File, com.senthuran.GRPCFileUpload.File.Builder, com.senthuran.GRPCFileUpload.FileOrBuilder> fileBuilder_;
    /**
     * <code>.File file = 2;</code>
     */
    public boolean hasFile() {
      return requestCase_ == 2;
    }
    /**
     * <code>.File file = 2;</code>
     */
    public com.senthuran.GRPCFileUpload.File getFile() {
      if (fileBuilder_ == null) {
        if (requestCase_ == 2) {
          return (com.senthuran.GRPCFileUpload.File) request_;
        }
        return com.senthuran.GRPCFileUpload.File.getDefaultInstance();
      } else {
        if (requestCase_ == 2) {
          return fileBuilder_.getMessage();
        }
        return com.senthuran.GRPCFileUpload.File.getDefaultInstance();
      }
    }
    /**
     * <code>.File file = 2;</code>
     */
    public Builder setFile(com.senthuran.GRPCFileUpload.File value) {
      if (fileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        fileBuilder_.setMessage(value);
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.File file = 2;</code>
     */
    public Builder setFile(
        com.senthuran.GRPCFileUpload.File.Builder builderForValue) {
      if (fileBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        fileBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.File file = 2;</code>
     */
    public Builder mergeFile(com.senthuran.GRPCFileUpload.File value) {
      if (fileBuilder_ == null) {
        if (requestCase_ == 2 &&
            request_ != com.senthuran.GRPCFileUpload.File.getDefaultInstance()) {
          request_ = com.senthuran.GRPCFileUpload.File.newBuilder((com.senthuran.GRPCFileUpload.File) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 2) {
          fileBuilder_.mergeFrom(value);
        }
        fileBuilder_.setMessage(value);
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.File file = 2;</code>
     */
    public Builder clearFile() {
      if (fileBuilder_ == null) {
        if (requestCase_ == 2) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 2) {
          requestCase_ = 0;
          request_ = null;
        }
        fileBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.File file = 2;</code>
     */
    public com.senthuran.GRPCFileUpload.File.Builder getFileBuilder() {
      return getFileFieldBuilder().getBuilder();
    }
    /**
     * <code>.File file = 2;</code>
     */
    public com.senthuran.GRPCFileUpload.FileOrBuilder getFileOrBuilder() {
      if ((requestCase_ == 2) && (fileBuilder_ != null)) {
        return fileBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 2) {
          return (com.senthuran.GRPCFileUpload.File) request_;
        }
        return com.senthuran.GRPCFileUpload.File.getDefaultInstance();
      }
    }
    /**
     * <code>.File file = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.senthuran.GRPCFileUpload.File, com.senthuran.GRPCFileUpload.File.Builder, com.senthuran.GRPCFileUpload.FileOrBuilder> 
        getFileFieldBuilder() {
      if (fileBuilder_ == null) {
        if (!(requestCase_ == 2)) {
          request_ = com.senthuran.GRPCFileUpload.File.getDefaultInstance();
        }
        fileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.senthuran.GRPCFileUpload.File, com.senthuran.GRPCFileUpload.File.Builder, com.senthuran.GRPCFileUpload.FileOrBuilder>(
                (com.senthuran.GRPCFileUpload.File) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 2;
      onChanged();;
      return fileBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FileUploadRequest)
  }

  // @@protoc_insertion_point(class_scope:FileUploadRequest)
  private static final com.senthuran.GRPCFileUpload.FileUploadRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.senthuran.GRPCFileUpload.FileUploadRequest();
  }

  public static com.senthuran.GRPCFileUpload.FileUploadRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FileUploadRequest>
      PARSER = new com.google.protobuf.AbstractParser<FileUploadRequest>() {
    @java.lang.Override
    public FileUploadRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FileUploadRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FileUploadRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileUploadRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.senthuran.GRPCFileUpload.FileUploadRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

