// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileUpload.proto

package com.senthuran.GRPCFileUpload;

public final class FileUpload {
  private FileUpload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_File_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_File_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MetaData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MetaData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileUploadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileUploadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileUploadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileUploadResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020fileUpload.proto\"\027\n\004File\022\017\n\007content\030\001 " +
      "\001(\014\"&\n\010MetaData\022\014\n\004name\030\001 \001(\t\022\014\n\004type\030\002 " +
      "\001(\t\"T\n\021FileUploadRequest\022\035\n\010metadata\030\001 \001" +
      "(\0132\t.MetaDataH\000\022\025\n\004file\030\002 \001(\0132\005.FileH\000B\t" +
      "\n\007request\";\n\022FileUploadResponse\022\014\n\004name\030" +
      "\001 \001(\t\022\027\n\006status\030\002 \001(\0162\007.Status*?\n\006Status" +
      "\022\013\n\007PENDING\020\000\022\017\n\013IN_PROGRESS\020\001\022\013\n\007SUCCES" +
      "S\020\002\022\n\n\006FAILED\020\0032H\n\021FileUploadService\0223\n\006" +
      "upload\022\022.FileUploadRequest\032\023.FileUploadR" +
      "esponse(\001B \n\034com.senthuran.GRPCFileUploa" +
      "dP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_File_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_File_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_File_descriptor,
        new java.lang.String[] { "Content", });
    internal_static_MetaData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MetaData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MetaData_descriptor,
        new java.lang.String[] { "Name", "Type", });
    internal_static_FileUploadRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FileUploadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileUploadRequest_descriptor,
        new java.lang.String[] { "Metadata", "File", "Request", });
    internal_static_FileUploadResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_FileUploadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileUploadResponse_descriptor,
        new java.lang.String[] { "Name", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
