// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileUpload.proto

package com.senthuran.GRPCFileUpload;

public interface MetaDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MetaData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string type = 2;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
